starlette_exporter/middleware.py, tests/test_middleware.py
I propose to add the `app_name` label for the metrics. Different fast api applications can be run in the same k8s cluster or on the same machine therefore it's good to have a easy way to distinguish applications.
=> Add app name to the metric name

README.md, starlette_exporter/__init__.py, starlette_exporter/middleware.py, tests/test_middleware.py
A small set of improvements — I can split them up into separate PRs if you need it.
Each commit is self-contained
1. Change middleware to be a generic ASGI3 middleware. Starlette is discouraging use of BaseHTTPMiddleware because it causes all sorts of problems with streaming requests & responses. eg: https://github.com/encode/starlette/issues/919#issuecomment-672908610 and others. Personally, I'm running into early EOFs during reading `request.stream()` when `PrometheusMiddleware` (or anything `BaseHTTPMiddleware`-derived) is active.
2. Use [`time.perf_counter()`](https://docs.python.org/3/library/time.html#time.perf_counter) instead of `time.time()`. It doesn't go backwards and it operates at a higher precision
5. Add prefix option for metric naming #3
=> ASGI3 and other misc improvements

starlette_exporter/__init__.py, starlette_exporter/middleware.py
Lowercase flag "prometheus_multiproc_dir" variable has been deprecated in favor of "PROMETHEUS_MULTIPROC_DIR"
Check [here](https://github.com/prometheus/client_python/blob/9118c02a9dfee530af9e83924a88be1ac4994bc0/prometheus_client/multiprocess.py#L30) for more information :)
Regards
=> Update multiproc env flag to uppercase (lowercase variable has been deprecated)

.github/workflows/test.yml, README.md
I'm grateful this package exists so figured a small contribution might be nice!
This addresses #25 by:
- Running the test suite against Python 3.6–3.10.
- Running the linting in a separate step so as not to repeat it for each Python version (it should be agnostic).
- Adding a notice to the README about supported Python versions ("3.6+").
=> Test against multiple Pythons

starlette_exporter/middleware.py
Support for FastAPI's root_path option (https://fastapi.tiangolo.com/advanced/behind-a-proxy/)
Fixes #38
=> support for FastAPI root_path option

README.md, starlette_exporter/middleware.py, tests/test_middleware.py
This pull request implements the `always_use_int_status` flag.
This flag attempts to convert the `status_code` value in a response to an integer.
This ensures consistent metrics when returning values with http.HTTPStatus code or an integer in the `status_code`.
Current behaviour will have produce duplicate metrics if somewhere else in the code uses can integer value.
=> Feature always use int status

README.md, setup.py, starlette_exporter/__init__.py, starlette_exporter/labels.py, starlette_exporter/middleware.py, tests/test_middleware.py
Adds a `labels` argument to `PrometheusMiddleware` that accepts a dict of labels/values that will be added to all metrics.
Each label's value can be either a static value or, optionally, a callback function that takes the Request instance as its argument and returns a string.
Example:
```python
app.add_middleware(
PrometheusMiddleware,
labels={
"service": "api",
"env": os.getenv("ENV")
}
```
=> User-supplied labels

.github/workflows/test.yml, README.md, requirements.txt, setup.py, starlette_exporter/__init__.py, starlette_exporter/middleware.py, tests/test_middleware.py
Add exemplar support (see README for documentation).
Also remove automated testing for Python 3.6 (it is EOL) and add it for Python 3.11.
Note: testing this PR with Python 3.11 surfaced a minor breaking change for 3.11 HTTPStatus enums:  If you are using HTTPStatus in your FastAPI app, values like `HTTPStatus.OK` in your Prometheus metrics output will likely just be recorded as `200` after Python 3.11.  This appears to be a Python change to `Enum` and unrelated to `starlette_exporter`.
=> add exemplar support

starlette_exporter/middleware.py
The current type annotation is working, but more narrow than the one from upstream:
* Allow any sequence, not only list
* Allow float values
Upstream is [here](https://github.com/prometheus/client_python/blob/1fd0ded5f8c9e7101471ea06198d88427728ff50/prometheus_client/metrics.py#L555).
=> Fix Type Annotations of buckets Parameter

README.md
The example snippets to configure the exporter in Starlette and FastAPI point to `openmetrics_handler` instead of `handle_metrics` (which is the function that is actually imported).
=> Fix `handle_metrics` references in `README.md`

starlette_exporter/__init__.py
Mypy in strict mode reports:
```
Mypy: Module "starlette_exporter" does not explicitly export attribute "PrometheusMiddleware"  [attr-defined]
```
=> Fix explicitly export attribute mypy error

README.md, setup.py, starlette_exporter/middleware.py, tests/test_middleware.py
Adds an option to avoid collecting metrics on request with specific methods.
This option can be used to avoid collecting metrics on, for example, communication description requests for endpoints (but can be used in any other method).
The new option is an optional list called `skip_methods`.
Example:
```python
app.add_middleware(
PrometheusMiddleware,
app_name="hello_world",
prefix='myapp',
labels={
"server_name": os.getenv("HOSTNAME"),
}),
group_paths=True,
buckets=[0.1, 0.25, 0.5],
skip_paths=['/health'],
skip_methods=['OPTIONS'],
always_use_int_status=False),
exemplars=lambda: {"trace_id": get_trace_id}  # function that returns a trace id
```
We have an application using microservices architecture, at the beginning of which there is a gateway that forwards requests with a given path or …
=> Include skip_methods option to avoid collecting metrics for specific methods

starlette_exporter/middleware.py
In the metrics, we were seeing a lot of requests with status code 500, which we did not see in the logs. It turned out that when a client closed the connection before a response was returned, it was reported as 500.
With this change, if the client closes the connection before a response was returned, 499 is used as status code (same code as nginx uses).
I think it's not possible to handle the `http.disconnect` event in `receive` since I think there is not guarantee that it will get called.
Unfortunately, I can't think of a way to test this, as the TestClient does [not send](https://github.com/encode/starlette/issues/1247) `http.disconnect` but it is working for us in production.
=> Use status code 499 for requests where the client closed the connection

starlette_exporter/middleware.py, tests/test_middleware.py
1. Fix handling of applications started using `uvicorn --root-path=/api`. Fixes #75.
Previously `PrometheusMiddleware` just threw away `root_path` from request scope. Because of this, `_get_router_path` always returned `None`, and if `PrometheusMiddleware` was used with both `group_paths=True` and `filter_unhandled_paths=True`, all application endpoints were just excluded from monitoring.
This requires `statlette>=0.33` because of https://github.com/encode/starlette/pull/2352.
2. Previously `__call__` method was implemented like this:
```python
try:
await self.app(scope, receive, send)
except Exception:
...
raise
finally:
if is_known_endpoint(path):
return
...
```
But [if the finally clause executes a return statement, exceptions are not …
=> Fix handling root_path

.github/workflows/test.yml, requirements.txt, setup.py, tests/test_middleware.py
Since starlette==0.35.0 https://github.com/encode/starlette/pull/2400 `scope["path"]` is now handled differently. This fixes different paths in tests `TestMiddleware.test_custom_root_path` and `TestMiddlewareGroupedPaths.test_custom_root_path`.
I'e updated the test, and also set minimal starlette version to 0.35. It does not support Python 3.7, so I've removed it from supported versions.
=> Update starlette to 0.35+

README.md, starlette_exporter/middleware.py, tests/test_middleware.py
=> skip_paths support regular expressions

starlette_exporter/middleware.py, tests/test_middleware.py
Inspect the exemplars function and pass the Request object, if a parameter with type annotation Request exists OR if no such parameter exists but one with the name "request".
Fixes #90
=> Optionally inject Request to exemplars function.

README.md, setup.py, starlette_exporter/__init__.py, starlette_exporter/labels.py, starlette_exporter/middleware.py, tests/test_middleware.py
Adds a `from_response_label` helper function to extract a label value from a response.
Closes #73
=> from_response_label helper function

README.md, starlette_exporter/middleware.py, tests/test_middleware.py
**PR Title:** Add `group_unhandled_paths` Option to Enhance `filter_unhandled_paths` Functionality
Hello @stephenhillier and @Filipoliko,
Following the discussion in the previous PR and the suggestions made, I have created an alternative PR (based on @Filipoliko solution) for handling unhandled paths.
**Overview of the Changes:**
- Introduced the `group_unhandled_paths` option.
- `group_unhandled_paths`: Similar to `filter_unhandled_paths`, but instead of ignoring the requests, they are grouped under the `__unknown__` path. This option overrides `filter_unhandled_paths` by setting it to `False`. The default value is `False`.
**Reasoning:**
- This approach simplifies configuration by linking the two options, reducing potential user confusion.
- Ensures clear intent when configuring the …
=> [Feature] Add `group_unhandled_paths` Option to Enhance `filter_unhandled_paths` Functionality  #91

starlette_exporter/labels.py, starlette_exporter/middleware.py, tests/test_middleware.py
Labels set with the `from_response_header` helper function were not being set during unhandled exceptions, leading to a Prometheus client exception.
Also, the `from_response_header` function now uses a case-insensitive lookup of header keys.
=> ensure response header labels are populated during exceptions
